USE [master]
GO

/****** Object:  Database [VIMS]    Script Date: 10/02/2016 11:52:09 ******/
CREATE DATABASE [VIMS] ON  PRIMARY 
( NAME = N'VIMS', FILENAME = N'c:\Program Files\Microsoft SQL Server\MSSQL10_50.MSSQLSERVER\MSSQL\DATA\VIMS.mdf' , SIZE = 2048KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'VIMS_log', FILENAME = N'c:\Program Files\Microsoft SQL Server\MSSQL10_50.MSSQLSERVER\MSSQL\DATA\VIMS_log.ldf' , SIZE = 1024KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO

ALTER DATABASE [VIMS] SET COMPATIBILITY_LEVEL = 100
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [VIMS].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [VIMS] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [VIMS] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [VIMS] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [VIMS] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [VIMS] SET ARITHABORT OFF 
GO

ALTER DATABASE [VIMS] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [VIMS] SET AUTO_CREATE_STATISTICS ON 
GO

ALTER DATABASE [VIMS] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [VIMS] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [VIMS] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [VIMS] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [VIMS] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [VIMS] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [VIMS] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [VIMS] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [VIMS] SET  DISABLE_BROKER 
GO

ALTER DATABASE [VIMS] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [VIMS] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [VIMS] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [VIMS] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [VIMS] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [VIMS] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [VIMS] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [VIMS] SET  READ_WRITE 
GO

ALTER DATABASE [VIMS] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [VIMS] SET  MULTI_USER 
GO

ALTER DATABASE [VIMS] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [VIMS] SET DB_CHAINING OFF 
GO


